#!/usr/bin/env bash

set -e

currdir=$(cd "$(dirname $0)" && pwd -P)

source "${currdir}/../utils.sh"
source "${currdir}/vim-utils.sh"
source "${currdir}/plugins.sh"

is_a_clean_install=false

# ==========================
# === Check dependencies ===
# ==========================

if [[ ! $(command -v curl) ]]; then
  echo "curl is required"
  exit 1
fi

if [[ ! $(command -v git) ]]; then
  echo "git is required"
  exit 1
fi

# ========================
# ===~/.vim/ directory ===
# ========================

# The ~/.vim/ dir will be created, or used, and optionally backed up.
# It will also be possible to abort the install process.

if [[ ! -e ~/.vim ]]; then
  is_a_clean_install=true
else
  echo "The ~/.vim/ directory exists. Do you want to...?"
  select reply in "Use existing" "Backup and recreate" "Abort"; do
    case "${reply}" in
      "Use existing" )
        break ;;
      "Backup and recreate" )
        vim_bkp_dir="vim-$(utc_timestamp).bkp"
        mv -v ~/.vim "${HOME}/${vim_bkp_dir}"
        break ;;
      "Abort" )
        exit 1;;
    esac
  done
fi

echo "Ensure a complete ~/.vim dir structure"
mkdir -v -p ~/.vim/{bundle,autoload,colors,undo,swap,_disabled_plugins}

# ================
# === pathogen ===
# ================

# It will use pathogen if present, offer to install, or abort.

if $is_a_clean_install; then
  install_pathogen
elif [[ $(find ~/.vim -name pathogen.vim) ]]; then
  echo "pathogen.vim is already installed"
else
  echo "pathogen.vim is required to install the vim plugins, but it is not installed"
  select reply in "Install pathogen to handle your plugins" "Abort"; do
    case "${reply}" in
      "Install pathogen to handle your plugins" )
        install_pathogen
        break ;;
      "Abort" )
        echo "Note: pathogen.vim is required to install the vim plugins, aborting."
        exit 1 ;;
    esac
  done
fi

# =======================
# === Install plugins ===
# =======================

for plugin in ${ESSENTIALS[@]}; do
  install_plugin_with_pathogen "${plugin}"
done

for plugin in ${NICE_TO_HAVES[@]}; do
  install_plugin_with_pathogen "$plugin"
done

# =============
# === vimrc ===
# =============

echo "Do you want to link to the vimrc provided?"
read -p "(your vimrc will be backed up if present) [y/N]: " -r
echo

if [[ $REPLY =~ ^[Yy] ]]; then
  if [[ -e ~/.vimrc && ! -L ~/.vimrc ]]; then
    mv -v ~/.vimrc ~/vimrc.original
  fi

  ln -sfv "${HOME}/.vim/bundle/bouncing-vim/rc-files/vimrc" "${HOME}/.vimrc"
else
  echo "Inspect the provided vimrc for more info. ${HOME}/.vim/bundle/bouncing-vim/rc-files/vimrc"
  echo "Make sure your vimrc initializes pathogen"
fi

# =================
# === tmux.conf ===
# =================

echo "Some of the features require specific configuration."
echo "Your tmux.conf will be backed up."

read -p "Do you want to link to the tmux.conf provided? [y/N]: " -r
echo

if [[ $REPLY =~ ^[Yy] ]]; then
  if [[ -e ~/.tmux.conf && ! -L ~/.tmux.conf ]]; then
    echo "Backup original vimrc"
    mv -v ~/.tmux.conf ~/tmux.conf.original
  fi

  ln -vsf "${HOME}/.vim/bundle/bouncing-vim/rc-files/tmux.conf" "${HOME}/.tmux.conf"
else
  echo "Inspect the provided tmux.conf for more info."
  echo "-> ${HOME}/.vim/bundle/bouncing-vim/rc-files/tmux.conf"
fi
