#!/usr/bin/env bash

set -e

CURRDIR=$(cd "$(dirname $0)" && pwd -P)

source "${CURRDIR}/../utils.sh"
source "${CURRDIR}/vim-utils.sh"

vim_repo_dir="${HOME}/Downloads/vim-hg"
vim_source_dir="${HOME}/Downloads/vim-src"

pull_vim_repo "${vim_repo_dir}" "${vim_source_dir}"

# These variables have to computed after pulling, otherwise the source dir would
# not be available to get the necessary data.
version_full=$(get_vim_version_full "${vim_source_dir}")
packaged_version="2:${version_full}"
vim_package_dir="${HOME}/Downloads/vim_${version_full}_amd64-precise"

install_dependencies "${CURRDIR}/vim-deps-build-precise.txt"

vim_configure_and_make "${vim_source_dir}"

make_install_for_package "${vim_source_dir}" "${vim_package_dir}"

create_control_file "${vim_source_dir}" \
                    "${vim_package_dir}" \
                    "${CURRDIR}/vim-deps-runtime-precise.txt" \
                    "${CURRDIR}/vim-deb-package-control-file" \
                    "${packaged_version}" \

dpkg-deb --build "${vim_package_dir}"
