#!/usr/bin/env bash

set -e

CURRDIR=$(cd "$(dirname $0)" && pwd -P)

source "${CURRDIR}/../utils.sh"
source "${CURRDIR}/plugins.sh"

for plugin in ${ESSENTIALS[@]}; do
  install_tmp_plugin_with_pathogen "${plugin}"
done
