" .vimrc originally based on https://github.com/DawidJanczak/.vim/blob/master/.vimrc

" ================
" === Pathogen ===
" ================

execute pathogen#infect()
execute pathogen#helptags()

" ============
" === Temp ===
" ============

" Customise the Ack! command by always ignoring the log dir
if executable('ag')
  let g:ackprg = 'ag --nogroup --nocolor --column --ignore={log,tags}'
endif

" ======================
" === Spell language ===
" ======================

set spelllang=en_gb

" ==============
" === Basics ===
" ==============

set nocompatible " with VI
set nomodeline " Ignore vim directives in magic comments

" ===================
" === Colorscheme ===
" ===================

" set the TERM to 'screen-256color' in the .bashrc:
"
"   if [[ -n "$TMUX" ]]; then
"     export TERM=screen-256color
"   else
"     export TERM=xterm-256color
"   fi

" " Disable Background Color Erase (BCE) so that color schemes
" " work properly when Vim is used inside tmux and GNU screen.
" " See also http://snk.tuxfamily.org/log/vim-256color-bce.html
" if &term =~ '256color'
"   set t_ut=
" endif

" set background=dark
" let g:molokai_original = 1
" colorscheme molokai

" colorscheme agnostic

" colorscheme noctu

" colorscheme base16-default

" colorscheme default

" =============================
" === Solarized colorscheme ===
" =============================

" Force solarized display sensibly when the terminal emulator has a custom
" palette.
" These can be avoided if the terminal emulator has solarized palette.
" Use t_Co=16 instead if the terminal has a 16 solarized palette.
" set t_Co=256
" let g:solarized_termcolors=256
" let g:solarized_termcolors=16
" set term=screen-256color " try this as a last resort

" " Actual solarized theme options
" let g:solarized_underline=0
" let g:solarized_italic=0
" let g:solarized_bold=0
" let g:solarized_contrast="high"
" let g:solarized_visibility="high"
" let g:solarized_termtrans=1 " transparent terminal support
" set background=light
set background=dark
colorscheme solarized

" ==================================
" === Colors for MiniBufExplorer ===
" ==================================

" Custom colors for buffers...
" ...NOT CHANGED and NOT VISIBLE
autocmd ColorScheme * highlight MBENormal ctermfg=14
" ...CHANGED and NOT VISIBLE
autocmd ColorScheme * highlight MBEChanged ctermfg=199
" ...NOT CHANGED and VISIBLE
autocmd ColorScheme * highlight MBEVisibleNormal ctermfg=15
" ...CHANGED and VISIBLE
autocmd ColorScheme * highlight MBEVisibleChanged ctermfg=178
" ...NOT CHANGED, VISIBLE and ACTIVE
autocmd ColorScheme * highlight MBEVisibleActiveNormal ctermfg=40
" ...CHANGED, VISIBLE and ACTIVE
autocmd ColorScheme * highlight MBEVisibleActiveChanged ctermfg=199

" ==============
" === golang ===
" ==============
" From the readme at $GOROOT/misc/vim/readme.txt and https://github.com/jnwhiteh/vim-golang/blob/master/readme.txt
" Some Linux distributions set filetype in /etc/vimrc.
" Clear filetype flags before changing runtimepath to force Vim to reload them.
filetype off
filetype plugin indent off
set runtimepath+=$GOROOT/misc/vim
filetype plugin indent on
syntax on

if executable('go')
  autocmd FileType go autocmd BufWritePre <buffer> Fmt
  " Activate the compiler plugin with ":compiler go". To always enable the
  " compiler plugin in Go source files:
  " autocmd FileType go compiler go
endif

" ===============================
" === Filetype customizations ===
" ===============================

" http://beerpla.net/2008/04/02/how-to-add-a-vim-file-extension-to-syntax-highlighting/
syntax enable
filetype on
au BufNewFile,BufRead *.txt set filetype=markdown
au BufNewFile,BufRead *.md set filetype=markdown
au BufNewFile,BufRead *.erb set filetype=eruby.html
" Set filetype for specific names: <http://dailyvim.tumblr.com/post/1262764095/additional-ruby-syntax-highlighting>
autocmd BufRead,BufNewFile {Capfile,Gemfile,Rakefile,config.ru,.caprc,.irbrc,irb_tempfile*,.pryrc,Vagrantfile} set filetype=ruby
" It shouldn't be needed with the mustache.vim plugin
" au BufNewFile,BufRead *.mustache set filetype=html
