#!/usr/bin/env bash

set -e

CURRDIR=$(cd "$(dirname $0)" && pwd -P)

source "${CURRDIR}/utils.sh"
source "${CURRDIR}/vim-plugin-list.sh"

is_a_clean_install=false

# ==========================
# === Check dependencies ===
# ==========================

if [[ ! $(command -v curl) ]];  then echo "curl is required"; exit 1; fi
if [[ ! $(command -v git) ]];   then echo "git is required";  exit 1; fi

# ========================
# ===~/.vim/ directory ===
# ========================

# The ~/.vim/ dir will be created, or used, and optionally backed up.
# It will also be possible to abort the install process.

if [[ ! -e ~/.vim ]]; then
  is_a_clean_install=true
else
  echo "The ~/.vim/ directory exists. Do you want to...?"
  select reply in "Use existing" "Backup and recreate" "Abort"; do
    case "${reply}" in
      "Use existing" )
        break ;;
      "Backup and recreate" )
        vim_bkp_dir=
        mv -v "${HOME}/.vim" "${HOME}/vim-$(utc_timestamp).bkp"
        break ;;
      "Abort" )
        exit 1;;
    esac
  done
fi

ensure_vim_dir_structure

# ================
# === pathogen ===
# ================

# It will use pathogen if present, offer to install, or abort.

if $is_a_clean_install; then
  install_pathogen
elif has_pathogen; then
  echo "pathogen.vim is already installed"
else
  echo "pathogen.vim is required to install the vim plugins, but it is not installed"
  select reply in "Install pathogen to handle your plugins" "Abort"; do
    case "${reply}" in
      "Install pathogen to handle your plugins" )
        install_pathogen
        break ;;
      "Abort" )
        echo "Note: pathogen.vim is required to install the vim plugins, aborting."
        exit 1 ;;
    esac
  done
fi

# =============
# === vimrc ===
# =============

link_rcfile \
  "vimrc" \
  "
NOTE: Make sure your vimrc initializes pathogen.
You can also create a ~/.vimrc.after that will be loaded automatically."

# =================
# === tmux.conf ===
# =================

link_rcfile \
  "tmux.conf" \
  "NOTE: Make sure you add the required configuration. See the README."

# =======================
# === Install plugins ===
# =======================

for plugin in ${ESSENTIALS[@]}; do
  install_plugin_with_pathogen "${plugin}"
done
