#!/usr/bin/env bash

set -e

CURRDIR=$(cd "$(dirname $0)" && pwd -P)

HOME_DIR=$1

if [[ -z "${HOME_DIR}" ]]; then
  echo "The home dir must be passed, aborting."
  exit 1
fi

source "${CURRDIR}/utils.sh"
source "${CURRDIR}/vim-plugin-list.sh"

ensure_vim_dir_structure

install_pathogen

ln -sfv "${HOME_DIR}/.vim/bundle/bouncing-vim/rc-files/vimrc" "${HOME_DIR}/.vimrc"
ln -sfv "${HOME_DIR}/.vim/bundle/bouncing-vim/rc-files/tmux.conf" "${HOME_DIR}/.tmux.conf"

for github_project in ${ESSENTIALS[@]}; do
  clone_to_bundle_with_home "${github_project}" "${HOME_DIR}"
done
