#!/usr/bin/env bash

set -e

CURRDIR=$(cd "$(dirname $0)" && pwd -P)

source "${CURRDIR}/utils.sh"

if [[ -z $(ls_tmp_plugins) ]]; then
  echo "There are no temporary plugins to remove."
  exit 0
fi

echo "
The following plugins will be moved to ~/.vim/_disabled_plugins/
and timestamped, so that you can remove them safely if you want.
"

ls_tmp_plugins

echo
echo "Do you want to proceed?"
read -r
if [[ ! $REPLY =~ ^[Yy] ]]; then
  echo "Abort."
  exit 1
fi

archive_tmp_plugins
