#!/usr/bin/env bash

set -e

CURRDIR=$(cd "$(dirname $0)" && pwd -P)

source "${CURRDIR}/utils.sh"
source "${CURRDIR}/vim-plugin-list.sh"

echo "
This script allows you to install some plugins temporarily, for
example during a pairing session.
echo
It will:
- check if pathogen is installed
- clone the plugins from github...
- ...under ~/.vim/bundle with a name 'bouncing-vim-tmp-<plugin>'
- skip the plugins the are already installed

This is the list of plugins:
"

for plugin in ${ESSENTIALS[@]}; do
  echo "  - ${plugin}"
done

echo
echo "Do you want to proceed?"
read -r
if [[ ! $REPLY =~ ^[Yy] ]]; then
  echo "Aborting as requested."
  exit 1
fi

if ! has_pathogen; then
  echo "
pathogen.vim is required to use new temporary plugins
but it is not installed. Exiting now."
  exit 1
fi

for plugin in ${ESSENTIALS[@]}; do
  install_tmp_plugin_with_pathogen "${plugin}"
done
