#!/usr/bin/env bash

declare -a -r ESSENTIALS=(
   "lucabelmondo/bouncing-vim"
        "mileszs/ack.vim"
  "ygt-mikekchar/agnostic"
           "kien/ctrlp.vim"
       "fholgado/minibufexpl.vim"
     "scrooloose/nerdtree"
          "mikbe/rspec.vim"
       "ervandew/supertab"
      "godlygeek/tabular"
  "jeetsukumaran/vim-buffergator"
         "kchmck/vim-coffee-script"
    "altercation/vim-colors-solarized"
          "tpope/vim-commentary"
          "tpope/vim-fugitive"
          "tpope/vim-markdown"
        "terryma/vim-multiple-cursors"
          "tpope/vim-repeat"
          "tpope/vim-rails"
       "vim-ruby/vim-ruby"
          "tpope/vim-sensible"
          "tpope/vim-surround"
)

declare -a -r NICE_TO_HAVES=(
  "noahfrederick/vim-noctu"
   "chriskempson/base16-vim"
       "ekalinin/Dockerfile.vim"
     "chikamichi/mediawiki.vim"
         "tomasr/molokai"
       "mustache/vim-mustache-handlebars"
          "hdima/python-syntax"
         "SirVer/ultisnips"
          "honza/vim-snippets"
          "fatih/vim-go"
           "gerw/vim-HiLinkTrace"
         "rodjek/vim-puppet"
           "t9md/vim-ruby-xmpfilter"
       "benmills/vimux"
)
